server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 39.97.3.60:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'