server:
  port: 2002
spring:
  application:
    name: cloud-alibaba-seata-storage-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.97.3.60:3306/seata_storage?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 333
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: 39.97.3.60:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  mapper-locations: classpath:mapper/*.xml