server:
  port: 2001
spring:
  application:
    name: cloud-alibaba-seata-order-service
  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.97.3.60:3306/seata_order?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 333

  cloud:
    alibaba:
      seata:
        # 这里和Seata的file.conf文件中Service事务组的名称保持一致
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: 39.97.3.60:1111

mybatis:
  config-location: classpath:mybatis/mybatis-conf.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

feign:
  hystrix:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'